### ISSUE TITLE
xo breaks Windows compatibility in development

### ISSUE THREAD

**Issue by Borewit** [sindresorhus/file-type#260]
xo prevents causes `npm run test` to crash:

```console
TypeError: (0 , _ignore.getFileExtensions) is not a function
Occurred while linting C:\Users\Borewit\code\github\file-type\test.js:8
    at checkSourceValue (C:\Users\Borewit\code\github\file-type\node_modules\eslint-plugin-import\lib\rules\no-useless-path-segments.js:103:60)
    at checkSourceValue (C:\Users\Borewit\code\github\file-type\node_modules\eslint-module-utils\moduleVisitor.js:29:5)
    at checkSource (C:\Users\Borewit\code\github\file-type\node_modules\eslint-module-utils\moduleVisitor.js:34:5)
    at C:\Users\Borewit\code\github\file-type\node_modules\eslint\lib\util\safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (C:\Users\Borewit\code\github\file-type\node_modules\eslint\lib\util\safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (C:\Users\Borewit\code\github\file-type\node_modules\eslint\lib\util\node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (C:\Users\Borewit\code\github\file-type\node_modules\eslint\lib\util\node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode (C:\Users\Borewit\code\github\file-type\node_modules\eslint\lib\util\node-event-generator.js:294:14)
    at CodePathAnalyzer.enterNode (C:\Users\Borewit\code\github\file-type\node_modules\eslint\lib\code-path-analysis\code-path-analyzer.js:632:23)
```

**Comment by Borewit** [comment]
Working now for me, strange
