### ISSUE TITLE
stream does not work with simple got stream snippet

### ISSUE THREAD

**Issue by fiws** [sindresorhus/file-type#342]
I don't get why this simple code snippet does not work. 

I'm sure this is some kind of nodejs stream thing, but reading the docs of file-type i just expected this to work:

```js
const got = require('got');
const FileType = require('file-type');

const url = 'https://upload.wikimedia.org/wikipedia/en/a/a9/Example.jpg';

(async () => {
  const source = got.stream(url);
  console.log(await FileType.stream(source));
  // ( ↑ should do something with the stream instead of logging it)
})();
```

## Result

```
(node:31937) UnhandledPromiseRejectionWarning: Error: Failed to pipe. The response has been emitted already.
    at DuplexWrapper.proxy.pipe (/home/fiws/hydra/pot-api/node_modules/got/dist/source/as-stream.js:98:19)
    at pipe (internal/streams/pipeline.js:54:15)
    at Array.reduce (<anonymous>)
    at Function.pipeline (internal/streams/pipeline.js:94:18)
    at DuplexWrapper.<anonymous> (/home/fiws/hydra/pot-api/node_modules/file-type/core.js:1290:26)
    at Object.onceWrapper (events.js:427:28)
    at DuplexWrapper.emit (events.js:321:20)
    at emitReadable_ (_stream_readable.js:577:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
(node:31937) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:31937) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Borewit** [comment]
Can you have a look at this one @bencmbrook? It seems related to the `stream()` function.

**Comment by bencmbrook** [comment]
It looks like `got.stream` performs an HTTP response if a pipe isn't immediately attached. 

This will fix your code:

```diff
const got = require('got');
const FileType = require('file-type');
+ const { PassThrough ;} = require('stream');

const url = 'https://upload.wikimedia.org/wikipedia/en/a/a9/Example.jpg';

(async () => {
- const source = got.stream(url);
+ const source = got.stream(url).pipe(new PassThrough());
  console.log(await FileType.stream(source));
  // ( ↑ should do something with the stream instead of logging it)
})();
```

While I wouldn't call this a bug in `file-type`, it does make for a feature request, which is to expose a `Writable` or `TransformStream`.

**Comment by fiws** [comment]
thank you a lot. this solved my problem.

i don't think the normal user can expect that. Maybe document it or workaround somehow. Just a suggestion though.

You can close this issue if you want.

**Comment by bencmbrook** [comment]
Thanks, closing this with TransformStream request in #350
