### ISSUE TITLE
TypeSCript error "Must use import to load ES Module"

### ISSUE THREAD

**Issue by paul-uz** [sindresorhus/file-type#503]
I am importing this module using:

`import { FileExtension, fileTypeFromBuffer } from 'file-type';`

But when I tried to run my code, I get the following error:

> Must use import to load ES Module: /var/task/node_modules/file-type/index.js\nrequire() of ES modules is not supported.\nrequire() of /var/task/node_modules/file-type/index.js from /var/task/index.js is an ES module file as it is a .js file whose nearest parent package.json contains \"type\": \"module\" which defines all .js files in that package scope as ES modules.\nInstead rename /var/task/node_modules/file-type/index.js to end in .cjs, change the requiring code to use import(), or remove \"type\": \"module\" from /var/task/node_modules/file-type/package.json.\n

This is using v17.0.0

**Comment by paul-uz** [comment]
Nevermind. I eventually found a reply to someone else about this. Sadly I cannot use v17 as AWS Lambda does not support ESM, despite using Node14

**Comment by daveteu** [comment]
lambda need to use file-type@16.5.1 and probably won't ever be able to use file-type latest release since it's all esm now.
  🥲

**Comment by paul-uz** [comment]
@daveteu don't supposed you know of any alternative libraries?

**Comment by daveteu** [comment]
file-type is one of the better libraries. I'm currently switching to [magic-byte.js](https://www.npmjs.com/package/magic-bytes.js). It's lacking in providing the mime type for many common file types but I've submitted a pull request. The next release will probably be more comprehensive, though not as much as file-type.

**Comment by Luxcium** [comment]
```log
❯ ts-node "${PROJECT}/src/utilities/sharp-phash/__sharp-phash-working.ts"
${PROJECT}/src/packages/file-path/getPathWithStats.ts:4
import { FileTypes } from './tools';
                    ^
Error [ERR_REQUIRE_ESM]: require() of ES Module ${PROJECT}/node_modules/file-type/index.js from ${PROJECT}/src/packages/file-path/getPathWithStats.ts not supported.
Instead change the require of index.js in ${PROJECT}/src/packages/file-path/getPathWithStats.ts to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (${PROJECT}/src/packages/file-path/getPathWithStats.ts:4:21)
    at Module.m._compile (${HOME}/.nvm/versions/node/v17.5.0/lib/node_modules/ts-node/dist/index.js:786:29)
    at Object.require.extensions.<computed> [as .ts] (${HOME}/.nvm/versions/node/v17.5.0/lib/node_modules/ts-node/dist/index.js:788:16)
    at Object.<anonymous> (${PROJECT}/src/packages/file-path/utils/index.ts:4:26)
    at Module.m._compile (${HOME}/.nvm/versions/node/v17.5.0/lib/node_modules/ts-node/dist/index.js:786:29)
    at Object.require.extensions.<computed> [as .ts] (${HOME}/.nvm/versions/node/v17.5.0/lib/node_modules/ts-node/dist/index.js:788:16)
    at Object.<anonymous> (${PROJECT}/src/packages/file-path/tools/dirListWithFileType/currentPath.ts:4:17)
    at Module.m._compile (${HOME}/.nvm/versions/node/v17.5.0/lib/node_modules/ts-node/dist/index.js:786:29)
    at Object.require.extensions.<computed> [as .ts] (${HOME}/.nvm/versions/node/v17.5.0/lib/node_modules/ts-node/dist/index.js:788:16)
    at Object.<anonymous> (${PROJECT}/src/packages/file-path/tools/dirListWithFileType/index.ts:4:21)
    at Module.m._compile (${HOME}/.nvm/versions/node/v17.5.0/lib/node_modules/ts-node/dist/index.js:786:29)
    at Object.require.extensions.<computed> [as .ts] (${HOME}/.nvm/versions/node/v17.5.0/lib/node_modules/ts-node/dist/index.js:788:16)
    at Object.<anonymous> (${PROJECT}/src/utilities/sharp-phash/__sharp-phash-working.ts:7:31)
    at Module.m._compile (${HOME}/.nvm/versions/node/v17.5.0/lib/node_modules/ts-node/dist/index.js:786:29)
    at Object.require.extensions.<computed> [as .ts] (${HOME}/.nvm/versions/node/v17.5.0/lib/node_modules/ts-node/dist/index.js:788:16)
    at main (${HOME}/.nvm/versions/node/v17.5.0/lib/node_modules/ts-node/dist/bin.js:292:16)
    at Object.<anonymous> (${HOME}/.nvm/versions/node/v17.5.0/lib/node_modules/ts-node/dist/bin.js:405:5) {
  code: 'ERR_REQUIRE_ESM'
}

```
