### ISSUE TITLE
node 12 fresh install unexpected token

### ISSUE THREAD

**Issue by emimarz** [sindresorhus/file-type#533]
fresh install on node v12.8.1 give me this error
import * as strtok3 from 'strtok3';
       ^

SyntaxError: Unexpected token *
    at Module._compile (internal/modules/cjs/loader.js:811:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:879:10)
    at Module.load (internal/modules/cjs/loader.js:731:32)
    at Function.Module._load (internal/modules/cjs/loader.js:644:12)
    at Module.require (internal/modules/cjs/loader.js:771:19)
    at require (internal/modules/cjs/helpers.js:68:18)

I only import the library like this
import { fileTypeFromStream } from 'file-type';

and using like this
    const readStream = fs.createReadStream(path);
    const fileType = await fileTypeFromStream(readStream);

**Comment by Borewit** [comment]
Since version 17 file-type is a pure ES-Module. Looks like you try to use that in CommonJS module. For example: https://github.com/Borewit/file-type-example/tree/master/commonjs

If you are using TypeScript it is more tricky.

**Comment by Borewit** [comment]
Same as #525

**Comment by emimarz** [comment]
so what, how can i do to avoid that error or use the library with typescript
