### ISSUE TITLE
jest: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by chenliang0571** [sindresorhus/file-type#602]
file-type.spec.ts
```
import { fileTypeFromFile } from 'file-type';

describe('Test-TEMP', () => {
    describe('fileTypeFromFile', () => {
        it('Unicorn.png', async () => {
            const res = await fileTypeFromFile('Unicorn.png');
            expect(res?.ext).toBe('png');
        });
    });
});
```

package.json
```
{
  "name": "jestjs",
  "version": "1.0.0",
  "description": "",
  "main": "sum.js",
  "scripts": {
    "test": "jest"
  },
  "type": "module",
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@jest/globals": "^29.5.0",
    "@types/jest": "^29.5.2",
    "jest": "^29.5.0",
    "ts-jest": "^29.1.0"
  },
  "dependencies": {
    "file-type": "^18.5.0"
  }
}
```

error message:
```
$ npx jest file-type.spec.ts 
 FAIL  ./file-type.spec.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    sample/jestjs/node_modules/file-type/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import * as strtok3 from 'strtok3';
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module

    > 1 | import { fileTypeFromFile } from 'file-type';
        | ^
      2 |
      3 | describe('Test-TEMP', () => {
      4 |     describe('fileTypeFromFile', () => {

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1495:14)
      at Object.<anonymous> (file-type.spec.ts:1:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.815 s
Ran all test suites matching /file-type.spec.ts/i.
```

**Comment by chenliang0571** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
